# we define the name our service
service: hello-world

# We pin the version of the serverless cli we want to use
frameworkVersion: ">=1.1.0 <2.0.0"

# we specify which cloud provider we want to deploy to
# as well as the runtime, in this case python3.6
# and the region we wish to deploy to
provider:
  name: aws
  runtime: python3.6
  region: us-west-1

# We define our list of functions
functions:
  # our hello function
  hello:
    # the file name and the function that
    # makes up our function: simple(.py).hello()
    handler: simple.hello
    # We define the event we wish to trigger this with
    events:
      # in this case a simple HTTP GET Request
      # with CORS enabled
      - http:
          path: hello
          method: get
          cors: true
